# This workflow defines the Continuous Deployment (CD) process.
# It automatically deploys the application to the production server
# whenever code is pushed to the 'main' branch.

name: Deploy to Production

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Use a specific Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run linting and tests
        run: |
          npm run lint
          npm test

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # The user to log in as (e.g., 'ubuntu')
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's private SSH key
          script: |
            # Navigate to the application directory
            cd /path/to/your/app/auth/back
            
            # Pull the latest changes from the main branch
            git pull origin main
            
            # Install/update dependencies
            npm install --production
            
            # Reload the application with PM2 for zero-downtime deployment
            npm run reload
